In [11]:
%%timeit -n 100
import numpy as np
def add_col(A,m,i,j):
    n=A.shape[1]
    E=np.eye(n)
    if i==j:
        E[i,i]=m+1
    else:
        E[j,i]=m
    return A@E
def det1(A):
    n=A.shape[0]
    for i in range(n):
        for j in range(n):
            A[i,j]=float(A[i,j])
    d=1
    for i in range(n):
        if abs(A[i,i])<=1.0e-16:
            x=0
            for col in range(i+1,n):
                if A[i,col]!=0:
                    A=add_col(A,1,i,col)
                    break
                else:
                    x+=1
            if x==n-1-i:
                d=0
                break
            else:
                for row in range(i+1,n):
                    for col in range(n-1,i-1,-1):
                        A[row,col]-=A[row,i]*A[i,col]/A[i,i]
                d=d*A[i,i]
        else:
            for row in range(i+1,n):
                for col in range(n-1,i-1,-1):
                    A[row,col]-=A[row,i]*A[i,col]/A[i,i]
            d=d*A[i,i]
    d=round(d,5)
    return d
def inv(A):
    n=A.shape[0]
    d=det1(A)
    if d!=0:
        A_inv=np.array([])
        for k in range(n**2):
            A_inv=np.append(A_inv,0.0)
        A_inv=A_inv.reshape(n,n)
        for i in range(n):
            for j in range(n):
                B=np.array([])
                for k in range((n-1)**2):
                    B=np.append(B,0.0)
                B=B.reshape(n-1,n-1)
                for row in range(i):
                    for col in range(j):
                        B[row,col]=A[row,col]
                    for col in range(j+1,n):
                        B[row,col-1]=A[row,col]
                for row in range(i+1,n):
                    for col in range(0,j):
                        B[row-1,col]=A[row,col]
                    for col in range(j+1,n):
                        B[row-1,col-1]=A[row,col]
                A_inv[i,j]=((-1)**(i+j))*det1(B)/d
                A_inv[i,j]=round(A_inv[i,j],5)
        A_inv=A_inv. T
        return A_inv
    if abs(d)<=1.0e-16:
        s="Inverse is NOT possible:This is a singular matrix"
        return s
F=np.array([[1.0,2.0,3.0],[9.0,29.0,19.0],[200.0,39.0,18.0]])
G=inv(F)

667 µs ± 79.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%%timeit -n 100
import numpy as np
F=np.array([[1.0,2.0,3.0],[9.0,29.0,19.0],[200.0,39.0,18.0]])
G=np.linalg.inv(F)

11.2 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
import numpy as np
Y=np.random.rand(1000,1000)

In [22]:
Y=np.random.rand(500,500)
print(np.linalg.inv(Y))

[[ 7.23786731e+00  1.85393608e+00 -1.61743868e+01 ...  4.89377544e+00
  -2.55045142e+00 -7.55691121e+00]
 [ 3.22609765e+00  9.86973679e-01 -7.22237203e+00 ...  2.24013262e+00
  -1.07690024e+00 -3.41821126e+00]
 [ 5.03487500e-01 -8.85827568e-02 -6.84257031e-01 ...  1.18009282e-01
  -3.11353724e-01 -2.64575444e-01]
 ...
 [-1.45281876e+00 -5.59055482e-01  3.65724515e+00 ... -1.22948097e+00
   5.09510217e-01  1.58334423e+00]
 [-3.51177960e+00 -7.64644595e-01  7.72249210e+00 ... -2.27352576e+00
   1.23821747e+00  3.71722281e+00]
 [-6.31125538e-01 -2.90715737e-03  8.12098273e-01 ... -1.68450319e-01
   2.63170345e-01  3.80119315e-01]]


# Conversion of decimal number to 32 bit single precision IEEE-754 floating point representation

In [24]:
def list_inv(a):
    n=len(a)
    b=[]
    for i in range(n):
        b.append(a[n-1-i])
    return b
a=[1,2,3]
print(list_inv(a))

[3, 2, 1]


In [25]:
def int_bin(n):
    li=[]
    while n>0:
        a=n%2
        li.append(a)
        n=int(n/2)
    li=list_inv(li)
    return li
l=int_bin(25)
print(l)

[1, 1, 0, 0, 1]


In [39]:
def fr_bin(f):
    i=0
    li=[]
    while (f>0 and i<35):
        f=2*f
        if f>=1:
            li.append(1)
            f=f-1
            i+=1
        elif f<1:
            li.append(0)
            i+=1
    return li
print(fr_bin(0.374))

[0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1]


In [41]:
def sign_bit(n):
    li=[]
    if n>=0:
        li.append(0)
    if n<0:
        li.append(1)
    return li

In [19]:
print(int_bin(1))
print(fr_bin(0.0))

[1]
[]


In [35]:
def exp_bit(n):
    n=abs(n)
    if n<1:
        a=fr_bin(n)
        i=0
        while a[i]==0:
            i+=1
        i+=1
        bias_exp=127-i
        bin_bias_exp=int_bin(bias_exp)
        j=0
        while len(bin_bias_exp)<8:
            bin_bias_exp.insert(j,0)
            j+=1
        return bin_bias_exp
    elif n>=1:
        int_n=int(n)
        b=int_bin(int_n)
        x=len(b)
        bia_exp=126+x
        bin_bia_exp=int_bin(bia_exp)
        k=0
        while len(bin_bia_exp)<8:
            bin_bia_exp.insert(k,0)
            k+=1
        return bin_bia_exp
print(exp_bit(0.5))

[0, 1, 1, 1, 1, 1, 1, 0]


In [40]:
def mantissa_bits(n):
    n=abs(n)
    if n<1:
        a=fr_bin(n)
        i=0
        while a[i]==0:
            del a[i]
            i+=1
        del a[i]
        while len(a)>23:
            del a[len(a)-1]
        return a
    elif n>=1:
        b=int(n)
        fr=n-b
        li=int_bin(b)+fr_bin(fr)
        del li[0]
        while len(li)>23:
            del li[len(li)-1]
        return li

In [55]:
n=.08429328
print(sign_bit(n))
print(exp_bit(n))
print(mantissa_bits(n))
print('\n')
a=-1.008429328
print(sign_bit(a))
print(exp_bit(a))
print(mantissa_bits(a))

[0]
[0, 1, 1, 1, 1, 0, 1, 1]
[0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1]


[1]
[0, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0]


In [5]:
import random
li=[]
for i in range(1000):
    a=random.randint(1,10)
    li.append(a)
for i in li:
    print(i )

6
1
10
2
7
7
5
10
3
4
2
5
10
9
3
4
9
4
3
8
5
3
9
5
5
4
10
9
10
4
5
7
8
3
2
10
5
5
7
4
8
10
2
6
10
4
2
5
8
3
2
10
8
2
9
5
7
7
9
5
2
5
9
7
9
8
3
4
10
1
2
5
2
1
3
5
9
7
2
9
1
5
4
7
6
8
4
3
7
10
6
6
2
5
8
7
10
4
4
9
10
8
10
3
4
2
3
10
7
5
5
4
4
8
5
7
8
4
8
7
5
7
3
3
6
3
4
8
7
6
7
10
6
6
10
4
10
9
4
2
8
6
9
8
3
9
5
8
5
6
3
9
5
9
6
4
7
4
9
2
5
4
2
1
6
9
4
4
6
2
10
6
7
9
1
7
4
1
4
5
2
8
6
9
1
5
3
5
1
5
3
6
4
7
4
8
10
10
2
7
5
7
3
2
2
6
10
4
7
1
8
5
2
5
9
2
5
10
2
4
6
1
1
6
8
9
4
1
8
4
4
4
3
10
3
7
2
10
4
3
9
7
6
7
6
8
4
7
8
6
4
2
5
6
7
2
7
1
1
3
10
3
3
2
1
6
9
1
6
2
7
4
4
5
1
6
10
2
4
2
5
4
5
2
2
5
5
10
1
4
7
7
4
1
6
8
1
4
10
3
2
9
2
9
10
2
6
8
9
2
10
6
3
5
6
1
10
6
3
4
8
9
5
4
10
5
1
4
6
1
2
3
5
7
3
1
10
9
2
10
1
10
5
8
4
1
10
10
8
10
6
7
1
4
6
7
2
3
3
3
5
6
2
9
4
10
8
9
6
1
9
3
5
10
10
6
10
9
1
6
3
4
4
5
3
3
1
3
7
6
6
6
2
8
2
9
7
2
10
8
1
6
6
6
4
8
1
2
6
9
2
9
9
1
10
9
1
6
6
3
2
6
9
9
2
7
10
5
7
3
2
1
9
3
10
3
2
6
7
3
7
10
3
9
1
7
7
8
1
9
6
7
4
7
3
5
3
3
3
1
1
10
5
9
6
10
6
3
7
9
6
9
2
10
5

In [61]:
R=int(input('Enter the number of random integers required:').split())
P=0
for i in range(len(R)):
    li=create_random_number(R[i],1,10)
    for i in range(len(li)):
        if li[i]==7:
            P +=1
    n=P/R
    print(f'P/R={n}')

Enter the number of random integers required:2 2 


TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [1]:
import numpy as np
a=np.random.rand(100,100)
print(a)

[[0.83324379 0.77650817 0.16974903 ... 0.70408962 0.9444083  0.69981322]
 [0.26777662 0.86294373 0.64770778 ... 0.23830148 0.46426375 0.58405688]
 [0.89317327 0.59875772 0.79619778 ... 0.38189362 0.27941066 0.48787609]
 ...
 [0.6176533  0.05815358 0.9950906  ... 0.16048321 0.56611359 0.47822316]
 [0.74010491 0.77212861 0.56397612 ... 0.23445528 0.11475221 0.95161936]
 [0.56159372 0.15932622 0.63240439 ... 0.211711   0.99386436 0.06226586]]
