In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [4]:
def det(A):
    '''
    Returns determinant of a SQUARE matrix
    '''
    n=A.shape[0]
    if n==1:
        d=A[0,0]
    elif n>=2:
        d=0
        for j in range(n):
            B=np.zeros((n-1)**2)
            B=B.reshape(n-1,n-1)
            for col in range(j):
                for row in range(1,n):
                    B[row-1,col]=A[row,col]
            for col in range(j+1,n):
                for row in range(1,n):
                    B[row-1,col-1]=A[row,col]
            d+=((-1)**j)*det(B)*A[0,j]
    return d 

In [5]:
E=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(det(E)) 

0.0


In [6]:
X=np.array([[1,2,3,4,5],[2,3,4,5,1],[3,4,5,1,2],[4,5,1,2,3],[5,1,2,3,4]])
print(det(X))

1875.0


In [2]:
def inv(A):
    '''
    Returns the inverse of a NON-SINGULAR SQUARE matrix
    '''
    n=A.shape[0]
    d=det1(A)
    if d!=0:
        A_inv=np.array([])
        for k in range(n**2):
            A_inv=np.append(A_inv,0.0)
        A_inv=A_inv.reshape(n,n)
        for i in range(n):
            for j in range(n):
                B=np.array([])
                for k in range((n-1)**2):
                    B=np.append(B,0.0)
                B=B.reshape(n-1,n-1)
                for row in range(i):
                    for col in range(j):
                        B[row,col]=A[row,col]
                    for col in range(j+1,n):
                        B[row,col-1]=A[row,col]
                for row in range(i+1,n):
                    for col in range(0,j):
                        B[row-1,col]=A[row,col]
                    for col in range(j+1,n):
                        B[row-1,col-1]=A[row,col]
                #Now B has become the minor of A[i,j]
                #So cofactor=((-1)**(i+j))*B
                A_inv[i,j]=((-1)**(i+j))*det1(B)/d
                A_inv[i,j]=round(A_inv[i,j],5)
        A_inv=A_inv. T
        return A_inv
    if abs(d)<=1.0e-16:
        s="Inverse is NOT possible:This is a singular matrix"
        return s

In [90]:
F=np.array([[1.0,2.0,3.0],[9.0,29.0,19.0],[200.0,39.0,18.0]])
print(inv(F))
G=np.linalg.inv(F)
print(G)

[[ 1.0000e+00 -1.8182e-01  5.2700e-03]
 [-0.0000e+00  9.0910e-02 -8.6000e-04]
 [-0.0000e+00 -0.0000e+00 -1.1800e-03]]
[[ 1.00000000e+00 -1.81818182e-01  5.27448870e-03]
 [ 0.00000000e+00  9.09090909e-02 -8.61141012e-04]
 [-0.00000000e+00 -0.00000000e+00 -1.18406889e-03]]


In [9]:
G=np.array([[1,2,3],[1,2,3],[4,23,33]])
print(inv(G))

Inverse is NOT possible:This is a singular matrix


In [51]:
a = np.array([])
for x in range(16):
    a = np.append(a, x)
a=a.reshape(4,4)
print(a)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [129]:
Y=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(np.max(Y))
#print(det1(Y))
Z=inv(Y)
print(Z)
print(np.linalg.inv(Y))

Inverse is NOT possible:This is a singular matrix


LinAlgError: Singular matrix

In [91]:
import timeit
test1='''
import numpy as np
def add_col(A,m,i,j):
    n=A.shape[1]
    E=np.eye(n)
    if i==j:
        E[i,i]=m+1
    else:
        E[j,i]=m
    return A@E
def det1(A):
    n=A.shape[0]
    for i in range(n):
        for j in range(n):
            A[i,j]=float(A[i,j])
    d=1
    for i in range(n):
        if abs(A[i,i])<=1.0e-16:
            x=0
            for col in range(i+1,n):
                if A[i,col]!=0:
                    A=add_col(A,1,i,col)
                    break
                else:
                    x+=1
            if x==n-1-i:
                d=0
                break
            else:
                for row in range(i+1,n):
                    for col in range(n-1,i-1,-1):
                        A[row,col]-=A[row,i]*A[i,col]/A[i,i]
                d=d*A[i,i]
        else:
            for row in range(i+1,n):
                for col in range(n-1,i-1,-1):
                    A[row,col]-=A[row,i]*A[i,col]/A[i,i]
            d=d*A[i,i]
    d=round(d,5)
    return d
def inv(A):
    n=A.shape[0]
    d=det1(A)
    if d!=0:
        A_inv=np.array([])
        for k in range(n**2):
            A_inv=np.append(A_inv,0.0)
        A_inv=A_inv.reshape(n,n)
        for i in range(n):
            for j in range(n):
                B=np.array([])
                for k in range((n-1)**2):
                    B=np.append(B,0.0)
                B=B.reshape(n-1,n-1)
                for row in range(i):
                    for col in range(j):
                        B[row,col]=A[row,col]
                    for col in range(j+1,n):
                        B[row,col-1]=A[row,col]
                for row in range(i+1,n):
                    for col in range(0,j):
                        B[row-1,col]=A[row,col]
                    for col in range(j+1,n):
                        B[row-1,col-1]=A[row,col]
                A_inv[i,j]=((-1)**(i+j))*det1(B)/d
                A_inv[i,j]=round(A_inv[i,j],5)
        A_inv=A_inv. T
        return A_inv
    if abs(d)<=1.0e-16:
        s="Inverse is NOT possible:This is a singular matrix"
        return s
F=np.array([[1.0,2.0,3.0],[9.0,29.0,19.0],[200.0,39.0,18.0]])
G=inv(F)
'''
print(timeit.timeit(stmt=test1))

500.0638128999999


In [86]:
import timeit
test2='''
import numpy as np
F=np.array([[1.0,2.0,3.0],[9.0,29.0,19.0],[200.0,39.0,18.0]])
Z=np.linalg.inv(F)
'''
print(timeit.timeit(stmt=test2))

10.199248200000511


In [4]:
Y=np.array([[1,2,3,4,5],[2,3,4,5,1],[3,4,5,1,2],[4,5,1,2,3],[5,1,2,3,4]])
Z=inv(Y)
print(Z)

[[-0.18667  0.01333  0.01333  0.01333  0.21333]
 [ 0.01333  0.01333  0.01333  0.21333 -0.18667]
 [ 0.01333  0.01333  0.21333 -0.18667  0.01333]
 [ 0.01333  0.21333 -0.18667  0.01333  0.01333]
 [ 0.21333 -0.18667  0.01333  0.01333  0.01333]]


In [13]:
Y=np.array([[1,2,3,4,5],[2,3,4,5,1],[3,4,5,1,2],[4,5,1,2,3],[5,1,2,3,4]])
Z=np.linalg.inv(Y)
print(inv(Y))
print(Z)

TypeError: only size-1 arrays can be converted to Python scalars

In [6]:
import numpy as np
def add_col(A,m,i,j):
    n=A.shape[1]
    E=np.eye(n)
    if i==j:
        E[i,i]=m+1
    else:
        E[j,i]=m
    return A@E
def det1(A):
    n=A.shape[0]
    for i in range(n):
        for j in range(n):
            A[i,j]=float(A[i,j])
    d=1
    for i in range(n):
        if abs(A[i,i])<=1.0e-16:
            x=0
            for col in range(i+1,n):
                if A[i,col]!=0:
                    A=add_col(A,1,i,col)
                    break
                else:
                    x+=1
            if x==n-1-i:
                d=0
                break
            else:
                for row in range(i+1,n):
                    for col in range(n-1,i-1,-1):
                        A[row,col]-=A[row,i]*A[i,col]/A[i,i]
                d=d*A[i,i]
        else:
            for row in range(i+1,n):
                for col in range(n-1,i-1,-1):
                    A[row,col]-=A[row,i]*A[i,col]/A[i,i]
            d=d*A[i,i]
    d=round(d,5)
    return d

In [10]:
A=np.array([[1.0,2.0,3.0],[4,5,6],[7,8,9]])
print(float(det1(A)))

0.0


In [20]:
%%timeit -n 1
s=0.0
for i in range(101):
    s+= sqrt(0.01*i*pi)*sin(0.01*pi*i)
print(s)

77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
335 µs ± 145 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%%timeit -n 1
import numpy as np
from math import pi,sin,sqrt
x=np.arange(0.0,1.01*pi,0.01*pi)
print(sum(np.sqrt(x)*np.sin(x)))

77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
77.5138979891651
The slowest run took 13.16 times longer than the fastest. This could mean that an intermediate result is being cached.
254 µs ± 295 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


In [20]:
a=3
a=float(a)
print(a)

3.0


In [35]:
a=1.0*2
print(type(a),a)

<class 'float'> 2.0


In [9]:
C = np.array([[5,5,5],[4,5,6],[7,8,9]])
print(det1(C))
#print(inv(C))
n=np.linalg.det(C)
format(n,'.30f')
#print(np.linalg.inv(C))

0


'0.000000000000000000000000000000'

# Solution of a system of n variable equations

In [10]:
array_of_coefficients=np.array([[3,5,-2],[1,1,1],[1,-2,4]])
array_of_constants=np.array([[4,1,6]])
array_of_constants=array_of_constants.reshape(3,1)
def solution(coeff_arr,const_arr):
    n=coeff_arr.shape[0]
    delta=det1(coeff_arr)
    if delta!=0:
        for i in range(n):
            

In [11]:
print 3

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(3)? (Temp/ipykernel_11724/48066052.py, line 1)

In [8]:
a=np.array([[1001,1002,1003],[2001,2002,2003],[3001,3002,3003]])
print(det1(a))

-1001.0
