In [1]:
import numpy as np
area=np.array([2.104,1.600,2.400,1.416,3.000])#thousand sq feet
area.reshape(5,1)
price=np.array([40.0,33.0,44.8,23.2,54.0]) #10000$
price.reshape(5,1)

array([[40. ],
       [33. ],
       [44.8],
       [23.2],
       [54. ]])

In [41]:
areat=np.array([2.104,1.600,2.400,1.416,3.000])
def res(th,dat_area,dat_price):
    import numpy as np
    m=dat_area.shape[0]
    n=th.shape[0]-1
    out=0.0
    for i in range(m):
        s=0.0
        for j in range(n+1):
            s+=th[j]*dat_area[i]
        out+=((s-dat_price[i])**2)/2
    return out
def sing_pred_cost(dat_area,dat_price,req_area):
    """
    Return required price corresponding to req_area
    """
    import numpy as np
    m=dat_area.shape[0]
    th=np.array([0.0,0.0])
    j0=res(th,dat_area,dat_price)
    residual=j0
    while (abs(residual)>1.0e-7):
#         temp=0
#         for i in range(m):
#             temp+=th[0]+th[1]*dat_area[i]-dat_price[i]
        for j in range(2):
            if j==0:
                temp=0.0
                for i in range(m):
                    temp+=th[0]+th[1]*dat_area[i]-dat_price[i]
                th[j]=th[j]-0.001*temp
            else:
                temp=0.0
                for i in range(m):
                    temp+=(th[0]+th[1]*dat_area[i]-dat_price[i])*dat_area[i]
                th[j]=th[j]-0.001*temp
        j1=res(th,dat_area,dat_price)
        residual=j1-j0
        j0=j1
    return(th[0]+th[1]*req_area)

In [42]:
pred_cost(areat,price,1.8)

33.540983959916126

In [7]:
3000**2

9000000

In [22]:
price.shape

(5,)

In [50]:
#area=np.array([[1,1,1,1,1],[2.104,1.600,2.400,1.416,3.000]])
area=np.array([[1,2.104],[1,1.6],[1,2.4],[1,1.416],[1,3.0]])
def normal_eqn(dat_area,dat_price,req_par):
    area_tr=np.transpose(dat_area)
    temp1=(area_tr)@dat_area
    temp2=(area_tr)@dat_price
    th=(np.linalg.inv(temp1))@temp2
    return(hval(th,req_par))

In [44]:
normal_eqn(area,price,2)

array([37.13243928])

In [31]:
price=price.reshape(5,1)

In [32]:
price.shape

(5, 1)

In [33]:
area.shape

(2, 5)

In [36]:
area@price

array([[195.    ],
       [439.3312]])

In [37]:
np.transpose(area)

array([[1.   , 2.104],
       [1.   , 1.6  ],
       [1.   , 2.4  ],
       [1.   , 1.416],
       [1.   , 3.   ]])

In [4]:
np.loadtxt?

# Read matrix from file

In [6]:
inp = np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv", delimiter=',',skiprows=1)
#print(inp)

In [7]:
inp.shape

(1599, 17)

In [8]:
print(inp)

[[ 7.4         0.7         0.         ...  0.636      30.90909091
   0.608     ]
 [ 7.8         0.88        0.         ...  0.778      26.8
   0.829     ]
 [ 7.8         0.76        0.04       ...  0.742      36.
   0.744     ]
 ...
 [ 6.3         0.51        0.13       ...  0.826      13.79310345
   0.754     ]
 [ 5.9         0.645       0.12       ...  0.785      13.75
   0.6615    ]
 [ 6.          0.31        0.47       ...  0.727      23.33333333
   1.2075    ]]


In [32]:
par=np.array([[1,2.104,3],[1,1.6,3],[1,2.4,3],[1,1.416,2],[1,3.0,4]])
price=np.array([40.0,33.0,44.8,23.2,54.0]) #10000$
#price=price.reshape(5,1)
price.shape

(5,)

In [52]:
def mul_res(th,train_par,train_val):
    import numpy as np
    m=train_par.shape[0]
    n=train_par.shape[1]
    out=0.0
    for i in range(m):
        s=0.0
        for j in range(n):
            s+=th[j]*train_par[i][j]
        out+=((s-train_val[i])**2)/2
    return out

def hval(th,par):
    n=par.shape[0]
    out=th[0]
    for i in range(n):
        out+=th[i]*par[i]
    return out
def pred_cost(train_par,train_val,req_par):
    """
    Return required price corresponding to required parameters
    """
    import numpy as np
    m=train_par.shape[0]
    n=train_par.shape[1]
    th=np.zeros(n+1)
    #th=np.array([0.0,0.0])
    j0=mul_res(th,train_par,train_val)
    residual=j0
    while (abs(residual)>1.0e-7):
#         temp=0
#         for i in range(m):
#             temp+=th[0]+th[1]*dat_area[i]-dat_price[i]
        for j in range(n):
            if j==0:
                temp=0.0
#                 for i in range(m):
#                     temp+=th[0]+th[1]*dat_area[i]-dat_price[i]
                for i in range(m):
                    temp+=hval(th,train_par[i])-train_val[i]
                th[j]=th[j]-1.0e-7*temp
            else:
                temp=0.0
                for i in range(m):
                    temp+=(hval(th,train_par[i])-train_val[i])*train_par[i][j]
                th[j]=th[j]-1.0e-7*temp
        j1=mul_res(th,train_par,train_val)
        residual=j1-j0
        j0=j1
    return(hval(th,req_par))

In [56]:
req_par=np.array([1,2.2,3])
pred_cost(par,price,req_par)

40.064631293438616

In [38]:
mul_res(np.zeros(3),par,price)

4075.14

In [55]:
x = np.array([[1,2104,5,1,45],[1,1416,3,2,40],[1,1534,3,2,30],[1,852,2,1,36]])
y=np.array([460,232,315,178])
normal_eqn(x,y,np.array([1,1000,3,4,35]))

-8384.0