In [122]:
# def sigmoid(x, Θ_1, Θ_2):                                                        
#     z = (Θ_1*x + Θ_2).astype("float_")                                              
#     return 1.0 / (1.0 + np.exp(-z))                                                
def sigmoid(x,th):                     
    """
    x - mx(n+1)
    th- (n+1)x1
    """
    import numpy as np
    out=x@th
    z = (out).astype("float_")   
    print(z)
    return 1.0 / (1.0 + np.exp((-1)*z))                                                

In [102]:
# def log_likelihood(x, y, Θ_1, Θ_2):                                                                
#     sigmoid_probs = sigmoid(x, Θ_1, Θ_2)                                        
#     return np.sum(y * np.log(sigmoid_probs)
#                   + (1 - y) * np.log(1 - sigmoid_probs))  
def log_likelihood(x, y, th):    
    """
    th - (n+1)x1
    x - mx(n+1)
    y- mx1
    """
    m=y.shape[0]
    import numpy as np
    sigmoid_probs = sigmoid(x, th)                                        
    return (-1)*np.sum(y * np.log(sigmoid_probs)
                  + (1 - y) * np.log(1 - sigmoid_probs))/m

In [86]:
# def gradient(x, y, Θ_1, Θ_2):                                                         
#     sigmoid_probs = sigmoid(x, Θ_1, Θ_2)                                        
#     return np.array([[np.sum((y - sigmoid_probs) * x),                          
#                      np.sum((y - sigmoid_probs) * 1)]])
def gradient(x, y, th):             
    """
    th - (n+1)x1
    x - mx(n+1)
    y- mx1
    """
    m=y.shape[0]
    import numpy as np
    sigmoid_probs = sigmoid(x, th)        
    #print(sigmoid_probs.shape)
    out=np.sum(((sigmoid_probs-y)*x/m),axis=0)
    return(np.transpose(out))
#     return np.array([[np.sum((y - sigmoid_probs) * x),                          
#                      np.sum((y - sigmoid_probs) * 1)]])

In [87]:
# def hessian(x, y, Θ_1, Θ_2):                                                          
#     sigmoid_probs = sigmoid(x, Θ_1, Θ_2)                                        
#     d1 = np.sum((sigmoid_probs * (1 - sigmoid_probs)) * x * x)                  
#     d2 = np.sum((sigmoid_probs * (1 - sigmoid_probs)) * x * 1)                  
#     d3 = np.sum((sigmoid_probs * (1 - sigmoid_probs)) * 1 * 1)                  
#     H = np.array([[d1, d2],[d2, d3]])                                           
#     return H
def hessian(x, y,th): 
    """
    th - (n+1)x1
    x - mx(n+1)
    y- mx1
    """
    m=y.shape[0]
    sigmoid_probs = sigmoid(x,th)                     
#     d1 = np.sum((sigmoid_probs * (1 - sigmoid_probs)) * x * x)                  
#     d2 = np.sum((sigmoid_probs * (1 - sigmoid_probs)) * x * 1)                  
#     d3 = np.sum((sigmoid_probs * (1 - sigmoid_probs)) * 1 * 1)                  
#     H = np.array([[d1, d2],[d2, d3]])    
    out=((np.transpose(x))@(sigmoid_probs*(1-sigmoid_probs)*x))
    return out/m

In [2]:
def newtons_method(x, y):                                                             
    """
    :param x (np.array(float)): Vector of Boston House Values in dollars
    :param y (np.array(boolean)): Vector of Bools indicting if house has > 2 bedrooms:
    :returns: np.array of logreg's parameters after convergence, [Θ_1, Θ_2]
    th - (n+1)x1
    x - mx(n+1)
    y- mx1
    """
    # Initialize log_likelihood & parameters                                                                   
#     Θ_1 = 15.1                                                                     
#     Θ_2 = -.4 # The intercept term  
    n=x.shape[1]-1
    th=np.ones(n+1)
    th=th.reshape(n+1,1)
    Δl = np.Infinity                                                                
    l = log_likelihood(x, y,th)                                                                 
    # Convergence Conditions                                                        
    δ = .0000000001                                                                 
#     max_iterations = 15                                                            
#     i = 0                                                                           
    while abs(Δl) > δ:                                       
#         i += 1                                                                      
        g = gradient(x, y, th)      
       # print(g.shape)
        hess = hessian(x, y, th)    
        #print(hess.shape)
        H_inv = np.linalg.inv(hess)                                                 
        # @ is syntactic sugar for np.dot(H_inv, g.T)¹
        Δ = H_inv @ g                                                            
#         ΔΘ_1 = Δ[0][0]                                                              
#         ΔΘ_2 = Δ[1][0]                                                              
                                                                                    
#         # Perform our update step                                                    
#         Θ_1 += ΔΘ_1                                                                 
#         Θ_2 += ΔΘ_2             
        th = th-Δ
                                                                                    
        # Update the log-likelihood at each iteration                                     
        l_new = log_likelihood(x, y,th)                                                      
        Δl = l - l_new                                                           
        l = l_new                                                                
    return th

In [104]:
import numpy as np
x=np.array([[1.0,.74,0.7,0,1.9,0.076],[1.0,.78,0.88,0,2.6,0.098],[1.0,0.78,0.76,0.04,2.3,0.092]
           ,[1.0,1.12,0.28,0.56,1.9,0.075],[1.0,0.74,0.7,0,1.9,0.076],[1.0,0.74,0.66,0,1.8,0.075],[1.0,0.79,0.6,0.06,1.6,0.069]])
y=np.array([0.0,0.0,0.0,1.0,1.0,0.0,0.0])
y=y.reshape(7,1)

In [105]:
th1=newtons_method(x,y)

/tmp/ipykernel_7689/3463222381.py:12: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp((-1)*z))
/tmp/ipykernel_7689/50544785.py:14: RuntimeWarning: divide by zero encountered in log
  return (-1)*np.sum(y * np.log(sigmoid_probs)
/tmp/ipykernel_7689/50544785.py:14: RuntimeWarning: invalid value encountered in multiply
  return (-1)*np.sum(y * np.log(sigmoid_probs)
/tmp/ipykernel_7689/50544785.py:15: RuntimeWarning: divide by zero encountered in log
  + (1 - y) * np.log(1 - sigmoid_probs))/m
/tmp/ipykernel_7689/50544785.py:15: RuntimeWarning: invalid value encountered in multiply
  + (1 - y) * np.log(1 - sigmoid_probs))/m


In [23]:
np.sum?

In [43]:
def dot_val(th,X):
    """
    th - (n+1)x1
    X - 1x(n+1)
    """ 
    import numpy as np
    out=X@th
    return out[0][0]
def hval(th,X):
    """
    th - (n+1)x1
    X - 1x(n+1)
    """ 
    from math import exp
    out=1/(1+exp((-1)*dot_val(th,X)))
    return out
def probab(th,X,y):
    """
    X - mx(n+1)
    y- mx1
    th - (n+1)x1
    """
    from math import log
    ZERO=1.0e-16
    m=y.shape[0]
    n=th.shape[0]-1
    s=0.0
    for i in range(m):
        t=X[i].reshape(1,n+1)
        ht=hval(th,t)
        temp=y[i][0]
#         if (abs(ht)<=ZERO or abs(1-ht)<=ZERO):
#             return 'c'
        #print(ht)
        s+=temp*log(ht)+(1-temp)*log(1-ht)
    return s
def pred(X,y):
    """
    X - mx(n+1)
    y- mx1
    test - 1x(n+1)
    """
    ERR=1.0e-6
    import numpy as np
    alp=1.0e-4
    m=y.shape[0]
    n=X.shape[1]-1
    th=np.zeros(n+1)
    th=th.reshape(n+1,1)
    j0=probab(th,X,y)
    conv=j0
    print(conv)
    it=0
    w=0.9
    threq=th
    min_err=j0
    while (abs(min_err)>=ERR):
        for j in range(n+1):
            t=0.0
            for i in range(m):
                t1=X[i].reshape(1,n+1)
                t+=(y[i]-hval(th,t1))*X[i][j]
            th[j]=(1-w)*th[j]+w*alp*t
        j1=probab(th,X,y)
        if (abs(j1-j0)<abs(conv)):
            w=1.9
        else:
            w=0.9
        conv=j1-j0
        if (abs(conv)<abs(min_err)):
            th_req=th
            min_err=conv
        print(conv)
        j0=j1
        it+=1
    return th_req

In [1]:
223/320

0.696875

In [36]:
import numpy as np
us=[]
for i in range(17):
    us.append(i)
del us[11]
us

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16]

In [37]:
X=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=321,usecols=us)
X=np.c_[np.ones(1279),X]
for i in range(1279):
    X[i][1:18]=X[i][1:18]/10
print(X)
print(X.shape)

[[1.         0.98       0.066      ... 0.0793     2.80952381 0.10795   ]
 [1.         0.93       0.061      ... 0.071      3.48       0.1117    ]
 [1.         0.78       0.062      ... 0.0709     3.         0.07395   ]
 ...
 [1.         0.63       0.051      ... 0.0826     1.37931034 0.0754    ]
 [1.         0.59       0.0645     ... 0.0785     1.375      0.06615   ]
 [1.         0.6        0.031      ... 0.0727     2.33333333 0.12075   ]]
(1279, 17)


In [38]:
te=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=1,max_rows=320,usecols=us)
#print(te.shape)
te=np.c_[np.ones(320),te]
for i in range(320):
    te[i][1:18]=te[i][1:18]/10
print(te)
print(te.shape)

[[1.         0.74       0.07       ... 0.0636     3.09090909 0.0608    ]
 [1.         0.78       0.088      ... 0.0778     2.68       0.0829    ]
 [1.         0.78       0.076      ... 0.0742     3.6        0.0744    ]
 ...
 [1.         0.96       0.077      ... 0.0722     2.46666667 0.0935    ]
 [1.         0.98       0.066      ... 0.0793     2.80952381 0.10795   ]
 [1.         0.96       0.077      ... 0.0722     2.46666667 0.0935    ]]
(320, 17)


In [39]:
y=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=321,usecols=[11])
y=y.reshape(1279,1)
print(y)

[[1.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [1.]]


In [44]:
th1=pred(X,y)

-886.5352439361416
5.463720070134514
0.27395338062535757
-2.747078932155773
2.8069514936495352
-0.4799686417908333
-0.6693695962723041
0.9269288514689151
-0.28728941035979005
0.00312623276136037
0.3304900520630554
-0.3667505189375788
0.09211422495786792
0.05452078726818854
-0.255085539080369
0.23098144302366563
-0.005306668007733606
-0.2531809559568501
0.2840881775360913
-0.06923910189152593
-0.042131832088784904
0.19264232009106763
-0.17417139035649143
0.00202810882524318
0.19197517146017162
-0.21299858839097396
0.052730789081806506
0.032378778910242545
-0.1487159811648553
0.13422797280213672
-0.0018962025419568818
-0.14954235979428177
0.16655760434116473
-0.0403577416564076
-0.02567532963917074
0.11543900082722303
-0.10391791778488368
0.0003504334795252362
0.11725679864127869
-0.12935781367059462
0.03144427202346378
0.02063526764538892
-0.09206242626305539
0.08258484293321544
2.7917057877857587e-05
-0.09494222930709384
0.10458425663796334
-0.024895863043866484
-0.01723284007289294
0.

In [45]:
print(th1)

[[ 7.40920077e-03]
 [ 6.82345451e-03]
 [ 1.86986727e-05]
 [ 4.19531149e-04]
 [ 1.81379604e-03]
 [ 3.68319788e-05]
 [ 8.01590348e-03]
 [-5.82589635e-03]
 [ 7.36007068e-04]
 [ 2.44671444e-03]
 [ 7.64056575e-04]
 [ 1.08806871e-02]
 [ 6.84215044e-03]
 [ 3.42107517e-03]
 [ 8.00888506e-04]
 [ 9.86976496e-03]
 [ 6.46460516e-04]]


In [50]:
teans=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=1,max_rows=320,usecols=[11])
teans=teans.reshape(320,1)
print(teans)

[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.

In [48]:
c=0
for i in range(320):
    temp=te[i].reshape(1,17)
    if (hval(th1,temp)>=0.5 and teans[i]==1.0):
        c+=1
    elif (hval(th1,temp)<0.5 and teans[i]==0.0):
        c+=1

In [49]:
c

125

In [53]:
from math import exp
a=np.array([[1],[exp(1)],[exp(2)]])
b=np.array([[1],[2],[3]])
b*(np.log(a))

array([[0.],
       [2.],
       [6.]])

In [54]:
b-1

array([[0],
       [1],
       [2]])

In [135]:
from math import exp
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[1],[2],[3]])
exp(c.T@c)

1202604.2841647768

In [136]:
exp(14)

1202604.2841647768

In [66]:
sigmoid(a,b)

array([[0.99999917],
       [1.        ],
       [1.        ]])

In [70]:
c=a@b
c

array([[14],
       [32],
       [50]])

In [69]:
1/(1+np.exp(-1*c))

array([[0.99999917],
       [1.        ],
       [1.        ]])

In [126]:
X=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=1,max_rows=1279,usecols=us)
X=np.c_[np.ones(1279),X]
for i in range(1279):
    X[i][1]/=10
    X[i][6]/=10
    X[i][7]/=10
    X[i][11]/=10
    X[i][12]/=10
    X[i][15]/=100
print(X)
print(X.shape)

[[1.         0.74       0.7        ... 0.636      0.30909091 0.608     ]
 [1.         0.78       0.88       ... 0.778      0.268      0.829     ]
 [1.         0.78       0.76       ... 0.742      0.36       0.744     ]
 ...
 [1.         0.85       0.4        ... 0.61       0.33333333 1.995     ]
 [1.         0.7        0.69       ... 0.714      0.33333333 0.627     ]
 [1.         0.8        0.715      ... 0.615      0.62307692 0.7715    ]]
(1279, 17)


In [127]:
y=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=1,max_rows=1279,usecols=[11])
y=y.reshape(1279,1)
print(y)
print(y.shape)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [1.]
 [1.]]
(1279, 1)


In [128]:
te=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=1280,usecols=us)
#print(te.shape)
te=np.c_[np.ones(320),te]
for i in range(320):
    te[i][1]/=10
    te[i][6]/=10
    te[i][7]/=10
    te[i][11]/=10
    te[i][12]/=10
    te[i][15]/=100
print(te)
print(te.shape)

[[1.         0.98       0.3        ... 0.632      0.3        0.619     ]
 [1.         0.71       0.46       ... 0.717      0.19285714 0.6485    ]
 [1.         0.71       0.46       ... 0.717      0.19285714 0.6485    ]
 ...
 [1.         0.63       0.51       ... 0.826      0.13793103 0.754     ]
 [1.         0.59       0.645      ... 0.785      0.1375     0.6615    ]
 [1.         0.6        0.31       ... 0.727      0.23333333 1.2075    ]]
(320, 17)


In [129]:
teans=np.loadtxt("../Epoch/Selection_Hackathon/Dataset.csv",delimiter=',',skiprows=1,max_rows=320,usecols=[11])
teans=teans.reshape(320,1)
print(teans)
print(teans.shape)

[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.

In [134]:
th1=newtons_method(X,y)

[[21.33689091]
 [27.4978    ]
 [24.741     ]
 ...
 [24.61399333]
 [17.90869333]
 [27.47545692]]
[[21.33689091]
 [27.4978    ]
 [24.741     ]
 ...
 [24.61399333]
 [17.90869333]
 [27.47545692]]
[[21.33689091]
 [27.4978    ]
 [24.741     ]
 ...
 [24.61399333]
 [17.90869333]
 [27.47545692]]
[[-1.59396477e+13  1.09235652e+13  1.10739142e+12 ...  4.45548296e+13
   6.45823159e+11 -7.75113136e+13]
 [-2.05421327e+13  1.40776842e+13  1.42714456e+12 ...  5.74197899e+13
   8.32301020e+11 -9.98922762e+13]
 [-1.84826752e+13  1.26663219e+13  1.28406576e+12 ...  5.16631520e+13
   7.48858437e+11 -8.98775468e+13]
 ...
 [-1.83877953e+13  1.26012999e+13  1.27747407e+12 ...  5.13979419e+13
   7.45014211e+11 -8.94161649e+13]
 [-1.33786250e+13  9.16847637e+12  9.29466874e+11 ...  3.73962065e+13
   5.42058773e+11 -6.50575734e+13]
 [-2.05254414e+13  1.40662455e+13  1.42598494e+12 ...  5.73731340e+13
   8.31624742e+11 -9.98111097e+13]]


/tmp/ipykernel_7689/50544785.py:15: RuntimeWarning: divide by zero encountered in log
  + (1 - y) * np.log(1 - sigmoid_probs))/m
/tmp/ipykernel_7689/50544785.py:15: RuntimeWarning: invalid value encountered in multiply
  + (1 - y) * np.log(1 - sigmoid_probs))/m
/tmp/ipykernel_7689/4247586834.py:13: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp((-1)*z))
/tmp/ipykernel_7689/50544785.py:14: RuntimeWarning: divide by zero encountered in log
  return (-1)*np.sum(y * np.log(sigmoid_probs)
/tmp/ipykernel_7689/50544785.py:14: RuntimeWarning: invalid value encountered in multiply
  return (-1)*np.sum(y * np.log(sigmoid_probs)


In [115]:
c=0
for i in range(320):
    temp=te[i].reshape(1,17)
    if (hval(th1,temp)>=0.5 and teans[i]==1.0):
        c+=1
    elif (hval(th1,temp)<0.5 and teans[i]==0.0):
        c+=1
c
th1

array([[ 58.20116159, -80.21875   , -13.54296875, -17.56982422,
        -19.9296875 ,   5.70703125,   0.23688924,  -0.15343498,
        -61.46894472,  -0.34648613,  43.66601562,   5.97085871,
         32.1015625 ,  10.12109375, -42.1484375 ,   0.37661378,
         67.01953125],
       [ 58.20116159, -80.21875   , -13.54296875, -17.56982422,
        -19.9296875 ,   5.70703125,   0.23688924,  -0.15343498,
        -61.46894472,  -0.34648613,  43.66601562,   5.97085871,
         32.1015625 ,  10.12109375, -42.1484375 ,   0.37661378,
         67.01953125],
       [ 58.20116159, -80.21875   , -13.54296875, -17.56982422,
        -19.9296875 ,   5.70703125,   0.23688924,  -0.15343498,
        -61.46894472,  -0.34648613,  43.66601562,   5.97085871,
         32.1015625 ,  10.12109375, -42.1484375 ,   0.37661378,
         67.01953125],
       [ 58.20116159, -80.21875   , -13.54296875, -17.56982422,
        -19.9296875 ,   5.70703125,   0.23688924,  -0.15343498,
        -61.46894472,  -0.34648613,

In [124]:
np.ones?