In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
al=pd.read_csv("../Ubuntu_files/Epoch_Hackathon/Dataset.csv")
# Train:test ratio = 80:20
# Therefore, I am taking 1280 training data and 319 test data
# Here we are going to take index 960 to 1279 as test data and rest as training data
x1=pd.concat([al[:640],al[959:]])

In [4]:
# Dropping k_value, l_value, m_value, n_value features of training data
x2=x1.drop(['k_value','l_value','m_value','n_value'],axis=1)

# Extracting quality of training data in numpy array "y"
y1=x2['quality']
y2=y1.to_numpy()
y=y2.reshape(1280,1)

# Removing quality from training data
x=x2.drop('quality',axis=1).to_numpy() 

# Test data from file
te1=al[960:1279]    

# Extracting quality of test data in numpy array "teans"
teans1=te1['quality']   
teans2=teans1.to_numpy()
teans=teans2.reshape(319,1)

# Since 'quality','k_value','l_value','m_value','n_value' are removed from training data, removing it from
# test data
te=te1.drop(['quality','k_value','l_value','m_value','n_value'],axis=1).to_numpy()

In [5]:
# Removing outliers from training data
temp1=np.percentile(x,1,axis=0)
temp99=np.percentile(x,99,axis=0)
c1=0
for col in range(12):
    p_1=temp1[col]
    p_99=temp99[col]
    for i in range(1280):
        if x[i][col]>p_99:
            x=np.delete(x,i,axis=0)
            y=np.delete(y,i,axis=0)
            c1+=1
        elif x[i][col]<p_1:
            x=np.delete(x,i,axis=0)
            y=np.delete(y,i,axis=0)
            c1+=1
        if (i==1279-c1):
            break

In [6]:
# Normalization of training data along with test data
n_row=x.shape[0]
for col in range(12):
    min_col=np.Infinity
    max_col=(-1)*np.Infinity
    for row in range(n_row):
        temp1=x[row][col]
        if (temp1>max_col):
            max_col=temp1
        elif (temp1<min_col):
            min_col=temp1
    x[:,col]=(x[:,col]-min_col)/(max_col-min_col)
    te[:,col]=(te[:,col]-min_col)/(max_col-min_col)

In [36]:
(x.T).shape

(12, 1113)

In [9]:
lsv,sv,rsv=np.linalg.svd(x.T)

In [10]:
lsv.shape

(12, 12)

In [11]:
sv.shape

(12,)

In [12]:
rsv.shape

(1113, 1113)

In [13]:
sv

array([2.17725527e+03, 5.60271793e+02, 2.83047879e+02, 8.57110348e+01,
       4.66004846e+01, 3.28652663e+01, 1.03592335e+01, 5.66660558e+00,
       4.18582440e+00, 3.01858964e+00, 9.14348470e-01, 7.27463939e-01])

In [16]:
lsv[:,:1]

array([[-0.11221488],
       [-0.00726374],
       [-0.00375558],
       [-0.03467646],
       [-0.00114816],
       [-0.25184701],
       [-0.8172403 ],
       [-0.01362507],
       [-0.0451559 ],
       [-0.00890299],
       [-0.13998342],
       [-0.48262743]])

In [28]:
def my_svd(A):
    """
    Return [lsv,svl,svr,rsv]
    A - nxm
    """
    import numpy as np
    temp,lsv=np.linalg.eig((A.T)@A)
    svl=np.sqrt(temp)
    temp,rsv=np.linalg.eig(A@(A.T))
    svr=np.sqrt(temp)
    li=[lsv,svl,svr,rsv]
    return li

In [18]:
np.linalg.eig?

In [29]:
li=my_svd(x)

In [52]:
len(li[1])

12

In [39]:
li[2].shape

(1113,)

In [46]:
li1=list(li[2])

In [49]:
li2=[i for i in li1 if i.imag==0]

In [54]:
len(li2)

49

In [56]:
li3=list(li[1])

In [57]:
len(li3)

12

In [59]:
c=0
for i in li2:
    if i in li3:
        print(i)

(10.359233484911412+0j)


In [60]:
li3

[2177.2552732851213,
 560.2717925055496,
 283.0478791449138,
 85.71103481523593,
 46.60048456360065,
 32.865266293495075,
 10.359233484911412,
 5.666605579162495,
 4.185824399134853,
 3.0185896385208566,
 0.727463938937246,
 0.9143484703004677]

In [61]:
li2

[(2177.2552732851204+0j),
 (560.2717925055488+0j),
 (283.047879144914+0j),
 (85.71103481523534+0j),
 (46.60048456360017+0j),
 (32.865266293495+0j),
 (10.359233484911412+0j),
 (5.666605579161543+0j),
 (4.185824399135257+0j),
 (3.0185896385234607+0j),
 (0.9143484702990669+0j),
 (0.7274639389394656+0j),
 (9.099906145315479e-06+0j),
 (7.567989075834715e-06+0j),
 (7.139077500003668e-06+0j),
 (6.664155407097181e-06+0j),
 (6.230949305912204e-06+0j),
 (6.0102480892621185e-06+0j),
 (5.385685740153787e-06+0j),
 (4.881847999912194e-06+0j),
 (4.665001603329779e-06+0j),
 (4.432709779944122e-06+0j),
 (3.680507706185761e-06+0j),
 (2.9644229975985413e-06+0j),
 (2.8752091177343546e-06+0j),
 (2.6184949155277696e-06+0j),
 (2.4545152194022604e-06+0j),
 (2.2594448872825852e-06+0j),
 (2.1601462181805413e-06+0j),
 (2.06435693278768e-06+0j),
 (1.9813392315999912e-06+0j),
 (1.7562071516293226e-06+0j),
 (1.474515307201477e-06+0j),
 (1.3476108135536919e-06+0j),
 (1.059126752942446e-06+0j),
 (8.862069241206369e-0

In [1]:
def PCA(x,k):
    """
    x - mxn
    k - number of principal components required
    Return the nxk matrix of principal orthonormal components
    """
    import numpy as np
    from math import sqrt
    m,n=x.shape
    xc=x
    xc=xc-np.sum(xc,axis=0)/(x.shape[0])
    σ=np.zeros(n)
    σ=σ.reshape(1,n)
    for i in range(n):
        σ[0][i]=0.0
        for j in range(m):
            σ[0][i]+=xc[j][i]**2
        σ[0][i]=sqrt(σ[0][i]/m)
    for i in range(n):
        for j in range(m):
            xc[j][i]=xc[j][i]/σ[0][i]
    emp_cov_mat=np.zeros(n*n)
    emp_cov_mat=emp_cov_mat.reshape(n,n)
    for i in range(m):
        temp=x[i].reshape(1,n)
        emp_cov_mat+=(temp.T)@temp
    emp_cov_mat=emp_cov_mat/m
    eigval,eigvect=np.linalg.eig(emp_cov_mat)
    return eigvect[:,:k]

In [74]:
xc=x

In [75]:
xc-np.sum(xc,axis=0)/(x.shape[0])

array([[-0.09139667,  0.15574707, -0.3678881 , ..., -0.0558741 ,
        -0.21440942, -0.00165441],
       [-0.05058034,  0.31364181, -0.3678881 , ...,  0.01685317,
        -0.1274529 , -0.03086596],
       [-0.05058034,  0.20837865, -0.31383405, ..., -0.00132865,
        -0.1274529 ,  0.03453689],
       ...,
       [-0.20364156, -0.01091959, -0.19221243, ...,  0.05927741,
         0.13341667, -0.12333205],
       [-0.24445789,  0.10750146, -0.20572594, ...,  0.03503499,
        -0.04049637, -0.12363847],
       [-0.23425381, -0.18635819,  0.26724703, ...,  0.00473196,
         0.13341667, -0.05551051]])

In [66]:
x.shape[0]

1113

In [76]:
np.sum?

In [79]:
np.sum(xc,axis=0)

array([351.58163265, 324.5745614 , 409.45945946, 122.0625    ,
       140.21974522, 289.89583333, 299.21167883, 533.11284047,
       540.48717949, 217.33333333, 335.42028985, 140.90641845])

In [81]:
np.linalg.eig?

In [11]:
a=PCA(x,5)

In [12]:
a.shape

(12, 5)

In [10]:
x.shape

(1113, 12)

In [13]:
from keras.datasets import mnist

ModuleNotFoundError: No module named 'keras'