In [224]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
al1=pd.read_csv("../Epoch/Selection_Hackathon/Dataset.csv")
#al=np.c_[np.ones(1599),al]
# #for col in range(17)
# for i in range(1599):
#     al[i][0]/=10
#     al[i][5]/=10
#     al[i][6]/=10
#     al[i][10]/=10
#     al[i][12]/=10
#     al[i][15]/=100

al1
# al1.shape

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  k_value  l_value  m_value  percentage_free_sulphur  \
0         9.4        0    8.100   4.0500    0.636                30.909091   
1         9.8        0    8.680   4.3400    0.778                26.800000   
2         9.8        0    8.560   4.2800    0.742                36.000000   
3         9.8        1   11.480   5.7400    0.655                35.294118   
4         9.4        0    8.100   4.0500    0.636                30.909091   
...       ...      ...      ...      ...      ...                      ...   
1594     10.5        0    6.800   3.4000    0.670                13.750000   
1595     11.2        1    6.450   3.2250    0.822                13.076923   
1596     11.0        1    6.810   3.4050    0.826                13.793103   
1597     10.2        0    6.545   3.2725    0.785                13.750000   
1598     11.0        1    6.310   3.1550    0.727                23.333333   

      n_value  
0      0.6080  
1      0.8290  
2      0.7440  
3      0.7195  
4      0.6080  
...       ...  
1594   0.6610  
1595   0.7110  
1596   0.7540  
1597   0.6615  
1598   1.2075  

[1599 rows x 17 columns]

In [251]:
al1.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity                 1.000000         -0.256131     0.671703   
volatile acidity             -0.256131          1.000000    -0.552496   
citric acid                   0.671703         -0.552496     1.000000   
residual sugar                0.114777          0.001918     0.143577   
chlorides                     0.093705          0.061298     0.203823   
free sulfur dioxide          -0.153794         -0.010504    -0.060978   
total sulfur dioxide         -0.113181          0.076470     0.035533   
density                       0.668047          0.022026     0.364947   
pH                           -0.682978          0.234937    -0.541904   
sulphates                     0.183006         -0.260987     0.312770   
alcohol                      -0.061668         -0.202288     0.109903   
quality                       0.095093         -0.321441     0.159129   
k_value                       0.994828         -0.156621     0.628252   
l_value                       0.994828         -0.156621     0.628252   
m_value                       0.184518         -0.215364     0.326059   
percentage_free_sulphur       0.029710          0.053302     0.067317   
n_value                       0.177790         -0.044542     0.241498   

                         residual sugar  chlorides  free sulfur dioxide  \
fixed acidity                  0.114777   0.093705            -0.153794   
volatile acidity               0.001918   0.061298            -0.010504   
citric acid                    0.143577   0.203823            -0.060978   
residual sugar                 1.000000   0.055610             0.187049   
chlorides                      0.055610   1.000000             0.005562   
free sulfur dioxide            0.187049   0.005562             1.000000   
total sulfur dioxide           0.203028   0.047400             0.667666   
density                        0.355283   0.200632            -0.021946   
pH                            -0.085652  -0.265026             0.070377   
sulphates                      0.005527   0.371260             0.051658   
alcohol                        0.042075  -0.221141            -0.069408   
quality                       -0.002160  -0.109494            -0.061757   
k_value                        0.117474   0.102184            -0.158242   
l_value                        0.117474   0.102184            -0.158242   
m_value                        0.018509   0.572840             0.046965   
percentage_free_sulphur        0.050021   0.081575            -0.217280   
n_value                        0.993575   0.127109             0.177675   

                         total sulfur dioxide   density        pH  sulphates  \
fixed acidity                       -0.113181  0.668047 -0.682978   0.183006   
volatile acidity                     0.076470  0.022026  0.234937  -0.260987   
citric acid                          0.035533  0.364947 -0.541904   0.312770   
residual sugar                       0.203028  0.355283 -0.085652   0.005527   
chlorides                            0.047400  0.200632 -0.265026   0.371260   
free sulfur dioxide                  0.667666 -0.021946  0.070377   0.051658   
total sulfur dioxide                 1.000000  0.071269 -0.066495   0.042947   
density                              0.071269  1.000000 -0.341699   0.148506   
pH                                  -0.066495 -0.341699  1.000000  -0.196648   
sulphates                            0.042947  0.148506 -0.196648   1.000000   
alcohol                             -0.205654 -0.496180  0.205633   0.093595   
quality                             -0.231963 -0.159110 -0.003264   0.218072   
k_value                             -0.107607  0.684886 -0.673141   0.159560   
l_value                             -0.107607  0.684886 -0.673141   0.159560   
m_value                              0.049530  0.180272 -0.238552   0.973757   
percentage_free_sulphur              0.331133  0.138697 -0.108620   0.055982   

In [252]:
x2=al1[319:]
x2

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
319             9.6             0.770         0.12             2.9      0.082   
320             9.8             0.660         0.39             3.2      0.083   
321             9.3             0.610         0.26             3.4      0.090   
322             7.8             0.620         0.05             2.3      0.079   
323            10.3             0.590         0.42             2.8      0.090   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
319                  30.0                  74.0  0.99865  3.30       0.64   
320                  21.0                  59.0  0.99890  3.37       0.71   
321                  25.0                  87.0  0.99975  3.24       0.62   
322                   6.0                  18.0  0.99735  3.29       0.63   
323                  35.0                  73.0  0.99900  3.28       0.70   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  k_value  l_value  m_value  percentage_free_sulphur  \
319      10.4        1   10.370   5.1850    0.722                24.666667   
320      11.5        1   10.460   5.2300    0.793                28.095238   
321       9.7        0    9.910   4.9550    0.710                34.800000   
322       9.3        0    8.420   4.2100    0.709                30.000000   
323       9.5        1   10.890   5.4450    0.790                20.857143   
...       ...      ...      ...      ...      ...                      ...   
1594     10.5        0    6.800   3.4000    0.670                13.750000   
1595     11.2        1    6.450   3.2250    0.822                13.076923   
1596     11.0        1    6.810   3.4050    0.826                13.793103   
1597     10.2        0    6.545   3.2725    0.785                13.750000   
1598     11.0        1    6.310   3.1550    0.727                23.333333   

      n_value  
319    0.9350  
320    1.0795  
321    1.1170  
322    0.7395  
323    0.9690  
...       ...  
1594   0.6610  
1595   0.7110  
1596   0.7540  
1597   0.6615  
1598   1.2075  

[1280 rows x 17 columns]

In [253]:
x2.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity                 1.000000         -0.234803     0.694993   
volatile acidity             -0.234803          1.000000    -0.548998   
citric acid                   0.694993         -0.548998     1.000000   
residual sugar                0.115441          0.022191     0.146532   
chlorides                     0.126669          0.104632     0.170754   
free sulfur dioxide          -0.176689         -0.003665    -0.093897   
total sulfur dioxide         -0.097132          0.080088     0.018942   
density                       0.673407          0.056491     0.370514   
pH                           -0.703530          0.239391    -0.556571   
sulphates                     0.187570         -0.303809     0.319358   
alcohol                      -0.084222         -0.216146     0.111457   
quality                       0.056497         -0.324944     0.173278   
k_value                       0.995086         -0.137405     0.652280   
l_value                       0.995086         -0.137405     0.652280   
m_value                       0.201973         -0.253268     0.333171   
percentage_free_sulphur       0.068428          0.035624     0.078150   
n_value                       0.178316         -0.021287     0.236947   

                         residual sugar  chlorides  free sulfur dioxide  \
fixed acidity                  0.115441   0.126669            -0.176689   
volatile acidity               0.022191   0.104632            -0.003665   
citric acid                    0.146532   0.170754            -0.093897   
residual sugar                 1.000000   0.105492             0.172775   
chlorides                      0.105492   1.000000            -0.014964   
free sulfur dioxide            0.172775  -0.014964             1.000000   
total sulfur dioxide           0.213624   0.023435             0.675179   
density                        0.354254   0.243609            -0.027713   
pH                            -0.106600  -0.226386             0.109533   
sulphates                      0.006579   0.239346             0.034167   
alcohol                        0.019838  -0.235253            -0.096660   
quality                       -0.009217  -0.105968            -0.060612   
k_value                        0.119895   0.139734            -0.180420   
l_value                        0.119895   0.139734            -0.180420   
m_value                        0.031178   0.457626             0.027721   
percentage_free_sulphur        0.065134   0.091852            -0.218451   
n_value                        0.994866   0.160477             0.160173   

                         total sulfur dioxide   density        pH  sulphates  \
fixed acidity                       -0.097132  0.673407 -0.703530   0.187570   
volatile acidity                     0.080088  0.056491  0.239391  -0.303809   
citric acid                          0.018942  0.370514 -0.556571   0.319358   
residual sugar                       0.213624  0.354254 -0.106600   0.006579   
chlorides                            0.023435  0.243609 -0.226386   0.239346   
free sulfur dioxide                  0.675179 -0.027713  0.109533   0.034167   
total sulfur dioxide                 1.000000  0.092848 -0.043089  -0.023155   
density                              0.092848  1.000000 -0.355177   0.130960   
pH                                  -0.043089 -0.355177  1.000000  -0.108005   
sulphates                           -0.023155  0.130960 -0.108005   1.000000   
alcohol                             -0.209228 -0.520120  0.203236   0.157046   
quality                             -0.193988 -0.192859 -0.005357   0.302395   
k_value                             -0.090820  0.691958 -0.692515   0.160189   
l_value                             -0.090820  0.691958 -0.692515   0.160189   
m_value                             -0.015616  0.178015 -0.152886   0.972832   
percentage_free_sulphur              0.289997  0.164936 -0.118515   0.043507   

In [254]:
x2=x2.drop(['k_value','l_value','m_value','n_value'],axis=1)

In [255]:
x2

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
319             9.6             0.770         0.12             2.9      0.082   
320             9.8             0.660         0.39             3.2      0.083   
321             9.3             0.610         0.26             3.4      0.090   
322             7.8             0.620         0.05             2.3      0.079   
323            10.3             0.590         0.42             2.8      0.090   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
319                  30.0                  74.0  0.99865  3.30       0.64   
320                  21.0                  59.0  0.99890  3.37       0.71   
321                  25.0                  87.0  0.99975  3.24       0.62   
322                   6.0                  18.0  0.99735  3.29       0.63   
323                  35.0                  73.0  0.99900  3.28       0.70   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  percentage_free_sulphur  
319      10.4        1                24.666667  
320      11.5        1                28.095238  
321       9.7        0                34.800000  
322       9.3        0                30.000000  
323       9.5        1                20.857143  
...       ...      ...                      ...  
1594     10.5        0                13.750000  
1595     11.2        1                13.076923  
1596     11.0        1                13.793103  
1597     10.2        0                13.750000  
1598     11.0        1                23.333333  

[1280 rows x 13 columns]

In [256]:
y2=x2['quality']

In [257]:
y2.shape

(1280,)

In [258]:
y=y2.to_numpy()

In [259]:
y=y.reshape(1280,1)

In [260]:
y

array([[1],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [261]:
x2.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  percentage_free_sulphur  
1594     10.5        0                13.750000  
1595     11.2        1                13.076923  
1596     11.0        1                13.793103  
1597     10.2        0                13.750000  
1598     11.0        1                23.333333

In [262]:
x=x2.drop('quality',axis=1).to_numpy()

In [263]:
x

array([[ 9.6       ,  0.77      ,  0.12      , ...,  0.64      ,
        10.4       , 24.66666667],
       [ 9.8       ,  0.66      ,  0.39      , ...,  0.71      ,
        11.5       , 28.0952381 ],
       [ 9.3       ,  0.61      ,  0.26      , ...,  0.62      ,
         9.7       , 34.8       ],
       ...,
       [ 6.3       ,  0.51      ,  0.13      , ...,  0.75      ,
        11.        , 13.79310345],
       [ 5.9       ,  0.645     ,  0.12      , ...,  0.71      ,
        10.2       , 13.75      ],
       [ 6.        ,  0.31      ,  0.47      , ...,  0.66      ,
        11.        , 23.33333333]])

In [264]:
temp1=x[:,11]
for i in range(1280):
    if temp1[i]>100.0:
        x=np.delete(x,i,axis=0)
        y=np.delete(y,i,axis=0)

In [265]:
x.shape

(1267, 12)

In [266]:
te=al1[:319]
te

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              7.4              0.70         0.00             1.9      0.076   
1              7.8              0.88         0.00             2.6      0.098   
2              7.8              0.76         0.04             2.3      0.092   
3             11.2              0.28         0.56             1.9      0.075   
4              7.4              0.70         0.00             1.9      0.076   
..             ...               ...          ...             ...        ...   
314            7.4              0.36         0.29             2.6      0.087   
315            7.1              0.35         0.29             2.5      0.096   
316            9.6              0.56         0.23             3.4      0.102   
317            9.6              0.77         0.12             2.9      0.082   
318            9.8              0.66         0.39             3.2      0.083   

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                   11.0                  34.0  0.99780  3.51       0.56   
1                   25.0                  67.0  0.99680  3.20       0.68   
2                   15.0                  54.0  0.99700  3.26       0.65   
3                   17.0                  60.0  0.99800  3.16       0.58   
4                   11.0                  34.0  0.99780  3.51       0.56   
..                   ...                   ...      ...   ...        ...   
314                 26.0                  72.0  0.99645  3.39       0.68   
315                 20.0                  53.0  0.99620  3.42       0.65   
316                 37.0                  92.0  0.99960  3.30       0.65   
317                 30.0                  74.0  0.99865  3.30       0.64   
318                 21.0                  59.0  0.99890  3.37       0.71   

     alcohol  quality  k_value  l_value  m_value  percentage_free_sulphur  \
0        9.4        0     8.10    4.050    0.636                30.909091   
1        9.8        0     8.68    4.340    0.778                26.800000   
2        9.8        0     8.56    4.280    0.742                36.000000   
3        9.8        1    11.48    5.740    0.655                35.294118   
4        9.4        0     8.10    4.050    0.636                30.909091   
..       ...      ...      ...      ...      ...                      ...   
314     11.0        0     7.76    3.880    0.767                27.692308   
315     11.0        1     7.45    3.725    0.746                26.500000   
316     10.1        0    10.16    5.080    0.752                24.864865   
317     10.4        1    10.37    5.185    0.722                24.666667   
318     11.5        1    10.46    5.230    0.793                28.095238   

     n_value  
0     0.6080  
1     0.8290  
2     0.7440  
3     0.7195  
4     0.6080  
..       ...  
314   0.8815  
315   0.8560  
316   1.1170  
317   0.9350  
318   1.0795  

[319 rows x 17 columns]

In [267]:
teans1=te['quality']

In [268]:
teans=teans1.to_numpy()

In [269]:
teans=teans.reshape(319,1)

In [270]:
teans

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [271]:
te=te.drop(['quality','k_value','l_value','m_value','n_value'],axis=1).to_numpy()

In [272]:
te

array([[ 7.4       ,  0.7       ,  0.        , ...,  0.56      ,
         9.4       , 30.90909091],
       [ 7.8       ,  0.88      ,  0.        , ...,  0.68      ,
         9.8       , 26.8       ],
       [ 7.8       ,  0.76      ,  0.04      , ...,  0.65      ,
         9.8       , 36.        ],
       ...,
       [ 9.6       ,  0.56      ,  0.23      , ...,  0.65      ,
        10.1       , 24.86486486],
       [ 9.6       ,  0.77      ,  0.12      , ...,  0.64      ,
        10.4       , 24.66666667],
       [ 9.8       ,  0.66      ,  0.39      , ...,  0.71      ,
        11.5       , 28.0952381 ]])

In [273]:
te.shape

(319, 12)

In [246]:
for col in range(12):
    min_col=np.Infinity
    max_col=(-1)*np.Infinity
    for row in range(1267):
        temp1=x[row][col]
        if (temp1>max_col):
            max_col=temp1
        elif (temp1<min_col):
            min_col=temp1
    x[:,col]=(x[:,col]-min_col)/(max_col-min_col)
    te[:,col]=(te[:,col]-min_col)/(max_col-min_col)

TypeError: '(slice(None, None, None), 0)' is an invalid key

In [274]:
te

array([[ 7.4       ,  0.7       ,  0.        , ...,  0.56      ,
         9.4       , 30.90909091],
       [ 7.8       ,  0.88      ,  0.        , ...,  0.68      ,
         9.8       , 26.8       ],
       [ 7.8       ,  0.76      ,  0.04      , ...,  0.65      ,
         9.8       , 36.        ],
       ...,
       [ 9.6       ,  0.56      ,  0.23      , ...,  0.65      ,
        10.1       , 24.86486486],
       [ 9.6       ,  0.77      ,  0.12      , ...,  0.64      ,
        10.4       , 24.66666667],
       [ 9.8       ,  0.66      ,  0.39      , ...,  0.71      ,
        11.5       , 28.0952381 ]])

In [275]:
x=np.c_[np.ones(1267),x]
te=np.c_[np.ones(319),te]

In [333]:
x1=x
temp1=np.percentile(x,1,axis=0)
temp99=np.percentile(x,99,axis=0)
c1=0
for col in range(13):
    p_1=temp1[col]
    p_99=temp99[col]
    for i in range(1267):
        if x1[i][col]>p_99:
            c1=c1+1
            x1=np.delete(x1,i,axis=0)
        elif x1[i][col]<p_1:
            x1=np.delete(x1,i,axis=0)
            c1=c1+1
        if (i==1267-c1-1):
            break

In [335]:
x1.shape

(1094, 13)

In [283]:
x.shape

(1267, 13)

In [285]:
temp1=np.percentile(x,1,axis=0)
temp99=np.percentile(x,99,axis=0)
print(temp1)
print(temp99)

[ 1.          5.3         0.1966      0.          1.4         0.042
  3.          8.          0.9917792   2.9332      0.42        9.
 13.09442971]
[  1.          13.3          1.0067       0.6934       8.8
   0.23772     51.         145.68         1.002134     3.7034
   1.17        13.4         87.71428571]


In [220]:
te.shape

(319, 13)

In [166]:
def j_th(th,x,y):
    import numpy as np
    m=x.shape[0]
    n=x.shape[1]-1
    temp=1.0/(1+np.exp(-1*(x@th)))
    out=(y*(np.log(temp))+(1-y)*(np.log(1-temp)))
    s=float(np.sum(out))
    return(-1*s/m)
def newt_method(x,y):
    EPS=1.0e-10
    m=x.shape[0]
    n=x.shape[1]-1
    th=np.zeros(n+1)
    th=th.reshape(n+1,1)
    conv=np.Infinity
    j0=j_th(th,x,y)
    it=0
    while abs(conv)>EPS:
        it+=1
        temp1=1.0/(1.0+np.exp(-1*x@th))
        H=((np.transpose(x))@((temp1)*(1-temp1)*x))
        H=H/m
        dJ=np.sum(((temp1-y)*x/m),axis=0)
        dJ=dJ.reshape(n+1,1)
        temp2=(np.linalg.pinv(H))@dJ
#         print(np.linalg.pinv(H))
#         print(dJ)
#         print(temp2)
        th=th-temp2
        j1=j_th(th,x,y)
        conv=j1-j0
        j0=j1
    print(it)
    return th

In [167]:
th=newt_method(x,y)

5


In [169]:
th

array([[-0.23896917],
       [ 0.09302693],
       [-3.86051702],
       [-0.56285904],
       [ 0.55505469],
       [-1.98356246],
       [ 1.61001612],
       [-4.03675705],
       [-0.50413675],
       [-1.48436018],
       [ 5.2310403 ],
       [ 5.92565295],
       [ 2.45340314]])

In [170]:
c=0
my_ans=1.0/(1.0+np.exp(-1*te@th))
for i in range(319):
    if (my_ans[i]>=0.57 and teans[i]==1.0):
        c+=1
    elif (my_ans[i]<0.57 and teans[i]==0.0):
        c+=1
c

224

In [172]:
224/319

0.7021943573667712

In [180]:
np.percentile(x,1,axis=0)

array([1.        , 0.03636364, 0.05246575, 0.        , 0.03424658,
       0.07317073, 0.02816901, 0.00706714, 0.12549192, 0.06365217,
       0.04      , 0.09230769, 0.0033333 ])

In [222]:
x.shape

In [310]:
arr = np.array([[0,4,1,9],[4,2,0,1]])
arr

array([[0, 4, 1, 9],
       [4, 2, 0, 1]])

In [312]:
arr1 = arr[(arr[0] < 8) & (arr[0] > 0)]
arr1

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4

In [299]:
li=[]
for i in range(13):
    li.append(i+1)

In [305]:
x.shape

(1267, 13)

In [308]:
x2=x
temp1=np.percentile(x2,1,axis=0)
temp99=np.percentile(x2,99,axis=0)
x3=x2.T
print(x3.shape)
for i in range(0,13):
    x3 = x3[(x3[i]>temp1[i]) & (x3[i]<temp99[i])]

(13, 1267)


IndexError: boolean index did not match indexed array along dimension 0; dimension is 13 but corresponding boolean dimension is 1267

In [318]:
gh = 0
for i in range (0,12-gh):
    print(i)
    gh += 1
print(gh)

0
1
2
3
4
5
6
7
8
9
10
11
12
