In [107]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
al1=pd.read_csv("../Epoch/Selection_Hackathon/Dataset.csv")
x1=pd.concat([al1[:960],al1[1279:]])
# x1=al1[:1280]
# x1=al1[319:]
x2=x1.drop(['k_value','l_value','m_value','n_value'],axis=1)
y1=x2['quality']
y2=y1.to_numpy()
y=y2.reshape(1280,1)
x3=x2.drop('quality',axis=1).to_numpy()
te1=al1[960:1279]
# te1=al1[1280:]
# te1=al1[:319]
teans1=te1['quality']
teans2=teans1.to_numpy()
teans=teans2.reshape(319,1)
te2=te1.drop(['quality','k_value','l_value','m_value','n_value'],axis=1).to_numpy()
x=np.c_[np.ones(1280),x3]
te=np.c_[np.ones(319),te2]
temp1=np.percentile(x,1,axis=0)
temp99=np.percentile(x,99,axis=0)
c1=0
for col in range(13):
    p_1=temp1[col]
    p_99=temp99[col]
    for i in range(1280):
        if x[i][col]>p_99:
            x=np.delete(x,i,axis=0)
            y=np.delete(y,i,axis=0)
            c1+=1
        elif x[i][col]<p_1:
            x=np.delete(x,i,axis=0)
            y=np.delete(y,i,axis=0)
            c1+=1
        if (i==1279-c1):
            break
n_row=x.shape[0]
for col in range(1,13):
    min_col=np.Infinity
    max_col=(-1)*np.Infinity
    for row in range(n_row):
        temp1=x[row][col]
        if (temp1>max_col):
            max_col=temp1
        elif (temp1<min_col):
            min_col=temp1
    x[:,col]=(x[:,col]-min_col)/(max_col-min_col)
    te[:,col]=(te[:,col]-min_col)/(max_col-min_col)

In [96]:
def j_th(th,x,y):
    import numpy as np
    m=x.shape[0]
    n=x.shape[1]-1
    temp=1.0/(1+np.exp(-1*(x@th)))
    out=(y*(np.log(temp))+(1-y)*(np.log(1-temp)))
    s=float(np.sum(out))
    return(-1*s/m)
def newt_method(x,y):
    EPS=1.0e-12
    m=x.shape[0]
    n=x.shape[1]-1
    th=np.zeros(n+1)
    th=th.reshape(n+1,1)
    conv=np.Infinity
    j0=j_th(th,x,y)
    it=0
    while abs(conv)>EPS:
        it+=1
        temp1=1.0/(1.0+np.exp(-1*x@th))
        H=((np.transpose(x))@((temp1)*(1-temp1)*x))
        H=H/m
        dJ=np.sum(((temp1-y)*x/m),axis=0)
        dJ=dJ.reshape(n+1,1)
        temp2=(np.linalg.pinv(H))@dJ
#         print(np.linalg.pinv(H))
#         print(dJ)
#         print(temp2)
        th=th-temp2
        j1=j_th(th,x,y)
        conv=j1-j0
        j0=j1
    print(it)
    return th

In [102]:
th1=newt_method(x,y)

5


In [103]:
th1

array([[-7.31624203e-01],
       [ 1.86167345e+00],
       [-3.41654565e+00],
       [-1.15128787e+00],
       [ 1.18701103e+00],
       [ 2.31863860e-01],
       [ 1.19475260e+00],
       [-2.71003369e+00],
       [ 8.23716287e-02],
       [ 6.75958270e-04],
       [ 4.24866765e+00],
       [ 4.27064036e+00],
       [-4.72777887e-01]])

In [109]:
c=0
my_ans=1.0/(1.0+np.exp(-1*te@th1))
for i in range(319):
    if (my_ans[i]>=0.57 and teans[i]==1.0):
        c+=1
    elif (my_ans[i]<0.57 and teans[i]==0.0):
        c+=1
c

253

In [34]:
x

array([[ 1.        ,  7.4       ,  0.7       , ...,  0.56      ,
         9.4       , 30.90909091],
       [ 1.        ,  7.8       ,  0.88      , ...,  0.68      ,
         9.8       , 26.8       ],
       [ 1.        ,  7.8       ,  0.76      , ...,  0.65      ,
         9.8       , 36.        ],
       ...,
       [ 1.        ,  6.3       ,  0.51      , ...,  0.75      ,
        11.        , 13.79310345],
       [ 1.        ,  5.9       ,  0.645     , ...,  0.71      ,
        10.2       , 13.75      ],
       [ 1.        ,  6.        ,  0.31      , ...,  0.66      ,
        11.        , 23.33333333]])

In [35]:
y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [40]:
248/320

0.775

In [45]:
237/320

0.740625

In [50]:
226/320

0.70625

In [55]:
238/320

0.74375

In [82]:
224/320

0.7

In [83]:
(0.775+0.740625+0.70625+0.74375+0.7)/5

0.7331249999999999

In [88]:
224/320

0.7

In [89]:
236/320

0.7375

In [94]:
231/320

0.721875

In [100]:
228/320

0.7125

In [105]:
253/320

0.790625

In [106]:
(0.7+0.7375+0.721875+0.7125+0.790625)/5

0.7324999999999999